# @package _global_

epochs: 1
batch_size: 1
model: htdemucs # see demucs/train.py for the possibilities, and config for each model hereafter.
continue_pretrained: "955717e8"
optim:
  lr: 0.0006
test:
  every: 20
  sdr: false
dset:
  segment: 10
  shift: 1

htdemucs: # see demucs/htdemucs.py for a detailed description
  channels: 48
  bottom_channels: 512

augment:
  scale:
    proba: 0
  shift_same: true
  remix:
    proba: 0